### ISSUE TITLE
The setup script should pin a setuptools version instead of a range (or restrict the upper end of its range).

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/setup#19]
Failures don't hint that this is the issue except very indirectly if you know how pex goes about its business:
```
$ mkdir /tmp/test2 && cd /tmp/test2 && curl -sSL -O https://pantsbuild.github.io/setup/pants && chmod +x pants && cat << EOF > pants.ini
[GLOBAL]
pants_version: 1.2.1

plugins: [
    'pantsbuild.pants.contrib.go==%(pants_version)s',
    'pantsbuild.pants.contrib.scrooge==%(pants_version)s',
  ]
EOF
$ rm -rf .pants.d/ ~/.pex/ ~/.cache/pants/{setup,plugins,python_cache} ~/.cache/pip/
$ PEX_VERBOSE=5 ./pants -V
...
Installing setuptools, pip, wheel...done.
Requirement already satisfied (use --upgrade to upgrade): setuptools<31.0,>=5.4.1 in /home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/pants.wsboUf/install/lib/python2.7/site-packages
...
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x7fa3f385f290>
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x7fa3f37eec50>
pex: crawling link i=0 link=Link('file:///home/jsirois/.cache/pants/plugins') follow_links=False
pex: crawling link i=0 link=Link('https://pypi.python.org/simple/pantsbuild.pants.contrib.go/') follow_links=False
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x7fa3f37eed90>
pex: crawling link i=0 link=Link('https://pypi.python.org/simple/pantsbuild.pants.contrib.scrooge/') follow_links=False
pex: Validated pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz (md5=8f6f45cb794f5d4887d46730d73f7862)                                                                                                 
pex: Validated pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz (md5=8f6f45cb794f5d4887d46730d73f7862)
pex: Fetching https://pypi.python.org/packages/66/3d/633f69deee202cb1397c5c3f11721696891e8680a2ff29c930fbd4cd3094/pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz#md5=8f6f45cb794f5d4887d46730d73f7862: 63.8ms
pex: Fetching file:///home/jsirois/.cache/pants/plugins/pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz: 1.9ms                                                                                             
pex:   Fetching file:///home/jsirois/.cache/pants/plugins/pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz: 0.2ms
pex: Failed to translate SourcePackage(u'file:///tmp/tmpP1KhHj/pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz')
pex: Traceback (most recent call last):
  File "/home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/1.2.1/lib/python2.7/site-packages/pex/translator.py", line 101, in translate
    strict=(package.name not in ('distribute', 'setuptools')))
  File "/home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/1.2.1/lib/python2.7/site-packages/pex/installer.py", line 61, in __init__
    self._interpreter.binary, self.__class__.__name__))
IncapableInterpreter: Interpreter /home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/pants.wsboUf/install/bin/python2.7 not capable of running EggInstaller

pex: Translating /tmp/tmpP1KhHj/pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz into distribution: 6.8ms
Exception caught: (<class 'pex.resolver.Untranslateable'>)
  File "/home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/1.2.1/bin/pants", line 11, in <module>
    sys.exit(main())
...
  File "/home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/1.2.1/lib/python2.7/site-packages/pex/resolver.py", line 168, in build
    raise Untranslateable('Package %s is not translateable by %s' % (package, translator))

Exception message: Package SourcePackage(u'file:///home/jsirois/.cache/pants/plugins/pantsbuild.pants.contrib.scrooge-1.2.1.tar.gz') is not translateable by ChainedTranslator(EggTranslator, SourceTranslator)
```

Here, an existing setuptools version:
```
$ ls -l /home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/pants.wsboUf/install/lib/python2.7/site-packages | grep setuptools
drwxr-xr-x  4 jsirois jsirois   4096 Jan 30 19:19 setuptools
drwxr-xr-x  2 jsirois jsirois   4096 Jan 30 19:19 setuptools-21.2.1.dist-info
```

Saisfied the _setup_ script constraint of `setuptools<31.0,>=5.4.1`, but failed the `pex==1.1.13` constaint of:
```
$ cat /home/jsirois/.cache/pants/setup/bootstrap-Linux-x86_64/pants.wsboUf/install/lib/python2.7/site-packages/pex/version.py
# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

__version__ = '1.1.13'

SETUPTOOLS_REQUIREMENT = 'setuptools>=2.2,<20.11'
WHEEL_REQUIREMENT = 'wheel>=0.24.0,<0.30.0'
```

**Comment by jsirois** [comment]
This issue describes the underlying problem leading to https://github.com/pantsbuild/pants/issues/4202 and https://github.com/pantsbuild/pants/issues/4218

**Comment by jsirois** [comment]
I'm going to take the tack of pinning the version to `5.4.1` for sanity sake. If pex and pants work with that lower bound they should ... work with that lower bound.

**Comment by kwlzn** [comment]
note that in 1.3.x we bump pants' 3rdparty to `setuptools==30.0.0` [here](https://github.com/pantsbuild/pants/commit/98c8d1970e9725c426565f492ddc5a9744d97d7d) - but afaict the change made in #20 is only an initial version and will auto-upgrade via pip mechanics as needed - yeah?

**Comment by jsirois** [comment]
Should be the case since both the LHS and RHS of the diff pin a version != 5.4.1.
